linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - gocyclo
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  gosec:
    excludes:
      - G501
      - G401
      - G505
